<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="web.config" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="web.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="web.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Words" Version="26.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="IPO.Common.API" Version="2.0.424491" />
    <PackageReference Include="IPO.Configuration" Version="2.0.424214" />
    <PackageReference Include="IPO.CTC.HealthChecks" Version="2.0.424215" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi.Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPO.Dictionary.Data\IPO.Dictionary.Data.csproj" />
    <ProjectReference Include="..\IPO.Dictionary.Gateways\IPO.Dictionary.Gateways.csproj" />
    <ProjectReference Include="..\IPO.Dictionary.Models\IPO.Dictionary.Models.csproj" />
    <ProjectReference Include="..\IPO.Dictionary.Services\IPO.Dictionary.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="version">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
